### PR TITLE
Fix doc deletion

### PR DESCRIPTION
**Pull request by rzezeski**
bz1147

Make sure to remove "proxy object" when a document is deleted from
the index.

### CODE REVIEW

**Comment by jtuple** [comment]
Simple change and tested to work fine for me.

Any thoughts on adding an eunit test to verify deletion of the doc and proxy object? While riak_search_client has 0% test coverage, riak_index_doc is sitting around 68%. May make sense to flesh out the get/delete/etc funs in riak_index_doc. 

Then again, we have integration tests for search that likely his these funs, so not sure.

**Comment by rzezeski** [comment]
Let me see if I can get something basic in there to test this.  Adding it at eunit level might be a pain to do ATM because Search is a pain to eunit (have plans to address that) but I imagine adding it to one of the integration tests shouldn't be too hard.  These are located in riak/tests/riak_search BTW, which I'm sure isn't obvious.

**Comment by jtuple** [comment]
Sounds good. Yeah, I ran the tests/riak_search tests before my first comment. But, I don't think we have a way to setup coverage for those (or at least not apparent to me), so it's hard to see what is/isn't tested. They seem to all use the solr interface which makes it doubly hard to test internal riak details like "proxy object" deleted as far as I know. Then again, my knowledge of these tests is limited so maybe they are more powerful than I think.

**Comment by jtuple** [comment]
All good, merge away. (Related PR: https://github.com/basho/riak/pull/58)

**Pull request merged**
