### PR TITLE
BZ953 - Change Riak Search to use the Whitespace analyzer by default. 

### PR DESCRIPTION
**Pull request by rustyio**
The default_analyzer_factory (or, in Java, the DefaultAnalyzerFactory) seems to trip everybody up because it tokenizes on punctuation, lowercases, and throws out stopwords and words smaller than 3 letters.

Try to reduce confusion by using the whitespace analyzer by default.

In order to stick to principle of least surprise, I made the following updates:
- Renamed default_analyzer_factory to standard_analyzer_factory
- Remove any concept of a "default" analyzer. The user most now specify an analyzer_factory setting for the schema or field.
- Updated the analysis engine to complain loudly if an analyzer is not specified or can't be found.

Finally, updated test cases to stress both the whitespace analyzer and the standard analyzer.

### CODE REVIEW

**Comment by beerriot** [comment]
I'm getting some failures in the test suites with these changes.

```
$ ./run_all.sh 
/Users/bryan/work/riak_search/tests/date_test
/Users/bryan/work/riak_search/tests/delete_test
/Users/bryan/work/riak_search/tests/kv_test
/Users/bryan/work/riak_search/tests/qilr_test
    [ ] FAIL QUERY » -acc:AAD
        - ERROR2: {error,single_negated_term} : [{riak_search_op,preplan,1},
/Users/bryan/work/riak_search/tests/schema_test
/Users/bryan/work/riak_search/tests/schemachange_test
/Users/bryan/work/riak_search/tests/solr_test
    [ ] FAIL SOLR SELECT » AAC AAJ (q.op=and&q=AAC+AAJ&wt=xml&rows=999)
    [ ] FAIL SOLR SELECT » AAC AAJ (q.op=and&q=AAC+AAJ&wt=json&rows=999)
/Users/bryan/work/riak_search/tests/solrsort_test
/Users/bryan/work/riak_search/tests/standard_query_test
/Users/bryan/work/riak_search/tests/utf8_test
    [ ] FAIL QUERY » いろはにほへど
    [ ] FAIL QUERY » value:いろはにほへど
/Users/bryan/work/riak_search/tests/whitespace_query_test
    [ ] FAIL QUERY » key:keyAA*
    [ ] FAIL QUERY » key:keyAAA*
    [ ] FAIL QUERY » key:keyAA?
```

Also, when the solrsort_test runs, this error prints on the riaksearch Erlang console:

```
=ERROR REPORT==== 5-Jan-2011::10:49:38 ===
The analyzer_factory setting is not set. Check your schema.

=ERROR REPORT==== 5-Jan-2011::10:49:38 ===
Unable to parse request: {schema_setting_required,analyzer_factory}
[{qilr_analyzer,analyze,4},
 {riak_indexed_doc,'-analyze/2-fun-0-',4},
 {lists,foldl,3},
 {riak_indexed_doc,analyze,2},
 {riak_indexed_doc,analyze,1},
 {riak_solr_search_client,'-parse_solr_xml/3-lc$^0/1-0-',4},
 {riak_solr_search_client,parse_solr_xml,3},
 {riak_solr_indexer_wm,malformed_request,2}]
```

I was able to squash similar errors in the kv and schema tests by adding an analyzer_factory setting to their schemas (https://github.com/rklophaus/riak_search/pull/1), but it looks to me like the schema for the solrsort already specifies an analyzer.

**Comment by rustyio** [comment]
The 'single_negated_term' error is expected and intentional. We just don't yet have support for negative tests in the test harness.

The two errors in "solr_test" are regression bugs tracked in bz://908.

The utf8_test errors should have a bug associated with them, but I can't seem to find it. Filed bug bz://963 to track those.

The three errors in whitespace_query_test are fixed in pull request: https://github.com/basho/riak_search/pull/32

**Comment by beerriot** [comment]
One more thing: if it's going to be the case that schemas that don't specify analyzers generate error messages, then these changes should include Big Flashy Warning Text about how to upgrade your cluster to avoid those errors.

Upgrading schemas before upgrading Search isn't really an option, though, if the names change, is it?  Maybe a dummy module to just pass along function calls would help?

**Comment by beerriot** [comment]
+1 merge

**Pull request merged**
