### PR TITLE
Add deprecation notice on Riak Search startup

### PR DESCRIPTION
**Pull request by coderoshi**
Yokozuna is the new hotness. Don't let people forget it with this classy deprecation notice.

basho/yokozuna#272

### CODE REVIEW

**Comment by rzezeski** [comment]
Two things:
1. I think it might be helpful to specify which version RS was deprecated so users don't have to search docs.
2. Other systems are deprecated for 2.0. We should try to be consistent with messaging. Something that perhaps PM wants to chime in on? I don't have any strong opinions on the wording, just thought I'd point it out.

**Comment by coderoshi** [comment]
1. We have other versions of RS?
2. I'm all for consistent messaging, though what other deprecation notices do we have.

**Comment by rzezeski** [comment]
1. I meant something like "deprecated since 2.0". Rereading the current message the "This version" confuses me. I dunno how to explain it but I would have expected something more like "Riak Search has been deprecated as of version 2.0.0. Please migrate to Yokozuna." Or something like that.
2. I think this is the first one. I just thought it was worth mentioning. I think this wording is fine but at some point we probably want some standard text to use for all cases for the sake of consistency. I figure PM might be interested in this messaging.

**Comment by coderoshi** [comment]
Alright, I like that wording. Even though we're branding the new search as Riak Search, I think calling it Yokozuna is still fine here, since it's talking about the underlying project.

**Comment by rzezeski** [comment]
+1

**Pull request merged**
